### ISSUE TITLE
5.18 Creating users in Kde User mannger does not work

### ISSUE THREAD

**Issue by architectlin** [ZaWertun/fedora-copr-kde5#25] opened 2020-02-13 08:08 UTC
file:///usr/share/kpackage/genericqml/org.kde.systemsettings.sidebar/contents/ui/SubCategoryPage.qml:141:9: QML Connections: Cannot assign to non-existent property "onActiveSubCategoryChanged"
QQmlEngine::setContextForObject(): Object already has a QQmlContext
Couldn't load plugin: "The shared library was not found."
Couldn't load plugin: "The shared library was not found."

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2056, resource id: 48253073, major code: 40 (TranslateCoords), minor code: 0

**Comment by ZaWertun** [comment] 2020-02-13 09:48
Just tried to create new user from KDE systemsettings & removing it - no problems seen.
Can you provide screenshot?

**Comment by architectlin** [comment] 2020-02-13 10:10
here the screenshot
![Screenshot_20200213_110154](https://user-images.githubusercontent.com/58938927/74423673-ea17cd00-4e50-11ea-9ce2-16950820a5ec.png)


even if i create a new user via console, and i log in with this account and try to create a new user the same problem exists, nothing happens

**Comment by ZaWertun** [comment] 2020-02-13 10:43
Still has no clue.
Try to reinstall packages `plasma-desktop` and `plasma-systemsettings` then reboot your PC.

Also check that all installed plasma packages has last version.
There is my list (output of command `rpm -qa |grep 5\\.18\\.0 |sort` from the console):
```
breeze-cursor-theme-5.18.0-1.fc31.noarch
breeze-gtk-5.18.0-1.fc31.noarch
kactivitymanagerd-5.18.0-1.fc31.x86_64
kde-cli-tools-5.18.0-1.fc31.x86_64
kdecoration-5.18.0-1.fc31.x86_64
kdecoration-devel-5.18.0-1.fc31.x86_64
kde-gtk-config-5.18.0-1.fc31.x86_64
kdeplasma-addons-5.18.0-1.fc31.x86_64
kdesu-5.18.0-1.fc31.x86_64
khotkeys-5.18.0-1.fc31.x86_64
kinfocenter-5.18.0-1.fc31.x86_64
kmenuedit-5.18.0-1.fc31.x86_64
kscreen-5.18.0-1.fc31.x86_64
kscreenlocker-5.18.0-1.fc31.x86_64
kscreenlocker-devel-5.18.0-1.fc31.x86_64
ksshaskpass-5.18.0-1.fc31.x86_64
ksysguard-5.18.0-1.fc31.x86_64
ksysguardd-5.18.0-1.fc31.x86_64
kwayland-integration-5.18.0-1.fc31.x86_64
kwin-5.18.0-1.fc31.x86_64
kwin-common-5.18.0-1.fc31.x86_64
kwin-libs-5.18.0-1.fc31.x86_64
kwin-wayland-5.18.0-1.fc31.x86_64
kwrited-5.18.0-1.fc31.x86_64
libkscreen-qt5-5.18.0-1.fc31.x86_64
libkscreen-qt5-devel-5.18.0-1.fc31.x86_64
libksysguard-5.18.0-1.fc31.x86_64
libksysguard-common-5.18.0-1.fc31.x86_64
libksysguard-devel-5.18.0-1.fc31.x86_64
libkworkspace5-5.18.0-3.fc31.x86_64
oxygen-sound-theme-5.18.0-1.fc31.noarch
pam-kwallet-5.18.0-1.fc31.x86_64
plasma-breeze-5.18.0-1.fc31.x86_64
plasma-breeze-common-5.18.0-1.fc31.noarch
plasma-browser-integration-5.18.0-1.fc31.x86_64
plasma-desktop-5.18.0-3.fc31.x86_64
plasma-desktop-debuginfo-5.18.0-3.fc31.x86_64
plasma-desktop-doc-5.18.0-3.fc31.noarch
plasma-drkonqi-5.18.0-1.fc31.x86_64
plasma-drkonqi-debuginfo-5.18.0-1.fc31.x86_64
plasma-integration-5.18.0-1.fc31.x86_64
plasma-lookandfeel-fedora-5.18.0-3.fc31.noarch
plasma-milou-5.18.0-1.fc31.x86_64
plasma-nm-5.18.0-1.fc31.x86_64
plasma-nm-l2tp-5.18.0-1.fc31.x86_64
plasma-nm-openconnect-5.18.0-1.fc31.x86_64
plasma-nm-openvpn-5.18.0-1.fc31.x86_64
plasma-nm-pptp-5.18.0-1.fc31.x86_64
plasma-nm-vpnc-5.18.0-1.fc31.x86_64
plasma-pa-5.18.0-1.fc31.x86_64
plasma-systemsettings-5.18.0-1.fc31.x86_64
plasma-systemsettings-debuginfo-5.18.0-1.fc31.x86_64
plasma-systemsettings-debugsource-5.18.0-1.fc31.x86_64
plasma-user-manager-5.18.0-1.fc31.x86_64
plasma-workspace-5.18.0-3.fc31.x86_64
plasma-workspace-common-5.18.0-3.fc31.x86_64
plasma-workspace-geolocation-5.18.0-3.fc31.x86_64
plasma-workspace-geolocation-libs-5.18.0-3.fc31.x86_64
plasma-workspace-libs-5.18.0-3.fc31.x86_64
polkit-kde-5.18.0-1.fc31.x86_64
powerdevil-5.18.0-1.fc31.x86_64
sddm-breeze-5.18.0-3.fc31.noarch
sddm-kcm-5.18.0-1.fc31.x86_64
xdg-desktop-portal-kde-5.18.0-1.fc31.x86_64
```

**Comment by architectlin** [comment] 2020-02-13 10:59
no changes, despite reinstallation of plasma-desktop and plasma-systemsettings and reboot

There is my list 

bluedevil-5.18.0-1.fc31.x86_64
breeze-cursor-theme-5.18.0-1.fc31.noarch
kactivitymanagerd-5.18.0-1.fc31.x86_64
kde-cli-tools-5.18.0-1.fc31.x86_64
kdecoration-5.18.0-1.fc31.x86_64
kde-gtk-config-5.18.0-1.fc31.x86_64
kdeplasma-addons-5.18.0-1.fc31.x86_64
kde-style-breeze-5.18.0-1.fc31.x86_64
kdesu-5.18.0-1.fc31.x86_64
khotkeys-5.18.0-1.fc31.x86_64
kinfocenter-5.18.0-1.fc31.x86_64
kmenuedit-5.18.0-1.fc31.x86_64
kscreen-5.18.0-1.fc31.x86_64
kscreenlocker-5.18.0-1.fc31.x86_64
ksshaskpass-5.18.0-1.fc31.x86_64
ksysguard-5.18.0-1.fc31.x86_64
ksysguardd-5.18.0-1.fc31.x86_64
kwayland-integration-5.18.0-1.fc31.x86_64
kwin-5.18.0-1.fc31.x86_64
kwin-common-5.18.0-1.fc31.x86_64
kwin-libs-5.18.0-1.fc31.x86_64
kwin-wayland-5.18.0-1.fc31.x86_64
kwrited-5.18.0-1.fc31.x86_64
libkscreen-qt5-5.18.0-1.fc31.x86_64
libksysguard-5.18.0-1.fc31.x86_64
libksysguard-common-5.18.0-1.fc31.x86_64
libkworkspace5-5.18.0-3.fc31.x86_64
oxygen-sound-theme-5.18.0-1.fc31.noarch
pam-kwallet-5.18.0-1.fc31.x86_64
plasma-breeze-5.18.0-1.fc31.x86_64
plasma-breeze-common-5.18.0-1.fc31.noarch
plasma-browser-integration-5.18.0-1.fc31.x86_64
plasma-desktop-5.18.0-3.fc31.x86_64
plasma-desktop-doc-5.18.0-3.fc31.noarch
plasma-discover-5.18.0-1.fc31.x86_64
plasma-discover-flatpak-5.18.0-1.fc31.x86_64
plasma-discover-libs-5.18.0-1.fc31.x86_64
plasma-discover-notifier-5.18.0-1.fc31.x86_64
plasma-discover-snap-5.18.0-1.fc31.x86_64
plasma-drkonqi-5.18.0-1.fc31.x86_64
plasma-integration-5.18.0-1.fc31.x86_64
plasma-lookandfeel-fedora-5.18.0-3.fc31.noarch
plasma-milou-5.18.0-1.fc31.x86_64
plasma-nm-5.18.0-1.fc31.x86_64
plasma-nm-l2tp-5.18.0-1.fc31.x86_64
plasma-nm-mobile-5.18.0-1.fc31.x86_64
plasma-nm-openconnect-5.18.0-1.fc31.x86_64
plasma-nm-openswan-5.18.0-1.fc31.x86_64
plasma-nm-openvpn-5.18.0-1.fc31.x86_64
plasma-nm-pptp-5.18.0-1.fc31.x86_64
plasma-nm-ssh-5.18.0-1.fc31.x86_64
plasma-nm-sstp-5.18.0-1.fc31.x86_64
plasma-nm-strongswan-5.18.0-1.fc31.x86_64
plasma-nm-vpnc-5.18.0-1.fc31.x86_64
plasma-pa-5.18.0-1.fc31.x86_64
plasma-systemsettings-5.18.0-1.fc31.x86_64
plasma-user-manager-5.18.0-1.fc31.x86_64
plasma-workspace-5.18.0-3.fc31.x86_64
plasma-workspace-common-5.18.0-3.fc31.x86_64
plasma-workspace-geolocation-5.18.0-3.fc31.x86_64
plasma-workspace-geolocation-libs-5.18.0-3.fc31.x86_64
plasma-workspace-libs-5.18.0-3.fc31.x86_64
plasma-workspace-wayland-5.18.0-3.fc31.x86_64
polkit-kde-5.18.0-1.fc31.x86_64
powerdevil-5.18.0-1.fc31.x86_64
sddm-breeze-5.18.0-3.fc31.noarch
sddm-kcm-5.18.0-1.fc31.x86_64
xdg-desktop-portal-kde-5.18.0-1.fc31.x86_64

**Comment by pizzadude** [comment] 2020-02-13 11:07
I can not reproduce this either.

Do you have any other kde coprs? If so, disable them and then do:

sudo dnf distro-sync

**Comment by architectlin** [comment] 2020-02-13 11:20
no changes for sudo dnf distro-sync

**Comment by architectlin** [comment] 2020-02-13 13:54
so the system was reinstalled
a new current iso was built for this purpose was available today

function in live system (from usb) works
Function new installed system goes

and after dnf copr enable zawertun/kde && dnf update --refresh
does not work!

**Comment by ZaWertun** [comment] 2020-02-16 14:19
After creatibng fresh VM with Fedora 31 and updating to packages from my repo - can't reproduce this bug.
Closing as invalid.

![Screenshot_20200216_171607](https://user-images.githubusercontent.com/1080298/74606311-7ee42a00-50e0-11ea-9c92-8cb54a8a5f41.png)

**Closed** 2020-02-16 14:19 UTC
Labels: invalid
